// Civic Commons Messaging Relay wire protocol (Task 4.4).
//
// Protocol Buffers over WebSocket frames (techstack §5.3). The client MUST
// authenticate in the FIRST frame (AuthRequest) — never in the URL, since
// query strings are logged by proxies.
//
// ZERO-KNOWLEDGE CONSTRAINT: the Envelope.ciphertext field is OPAQUE. The
// relay MUST never deserialize, decrypt, or inspect it — it routes bytes.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v7.35.1
// source: proto/relay.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientFrame is every message a client sends to the relay.
type ClientFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ClientFrame_Auth
	//	*ClientFrame_Envelope
	//	*ClientFrame_Ack
	Payload isClientFrame_Payload `protobuf_oneof:"payload"`
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_proto_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{0}
}

func (m *ClientFrame) GetPayload() isClientFrame_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ClientFrame) GetAuth() *AuthRequest {
	if x, ok := x.GetPayload().(*ClientFrame_Auth); ok {
		return x.Auth
	}
	return nil
}

func (x *ClientFrame) GetEnvelope() *Envelope {
	if x, ok := x.GetPayload().(*ClientFrame_Envelope); ok {
		return x.Envelope
	}
	return nil
}

func (x *ClientFrame) GetAck() *DeliveryAck {
	if x, ok := x.GetPayload().(*ClientFrame_Ack); ok {
		return x.Ack
	}
	return nil
}

type isClientFrame_Payload interface {
	isClientFrame_Payload()
}

type ClientFrame_Auth struct {
	Auth *AuthRequest `protobuf:"bytes,1,opt,name=auth,proto3,oneof"`
}

type ClientFrame_Envelope struct {
	Envelope *Envelope `protobuf:"bytes,2,opt,name=envelope,proto3,oneof"`
}

type ClientFrame_Ack struct {
	Ack *DeliveryAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*ClientFrame_Auth) isClientFrame_Payload() {}

func (*ClientFrame_Envelope) isClientFrame_Payload() {}

func (*ClientFrame_Ack) isClientFrame_Payload() {}

// ServerFrame is every message the relay sends to a client.
type ServerFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ServerFrame_AuthAck
	//	*ServerFrame_Envelope
	//	*ServerFrame_Ack
	//	*ServerFrame_Error
	Payload isServerFrame_Payload `protobuf_oneof:"payload"`
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_proto_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{1}
}

func (m *ServerFrame) GetPayload() isServerFrame_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ServerFrame) GetAuthAck() *AuthAck {
	if x, ok := x.GetPayload().(*ServerFrame_AuthAck); ok {
		return x.AuthAck
	}
	return nil
}

func (x *ServerFrame) GetEnvelope() *Envelope {
	if x, ok := x.GetPayload().(*ServerFrame_Envelope); ok {
		return x.Envelope
	}
	return nil
}

func (x *ServerFrame) GetAck() *DeliveryAck {
	if x, ok := x.GetPayload().(*ServerFrame_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *ServerFrame) GetError() *ErrorMessage {
	if x, ok := x.GetPayload().(*ServerFrame_Error); ok {
		return x.Error
	}
	return nil
}

type isServerFrame_Payload interface {
	isServerFrame_Payload()
}

type ServerFrame_AuthAck struct {
	AuthAck *AuthAck `protobuf:"bytes,1,opt,name=auth_ack,json=authAck,proto3,oneof"`
}

type ServerFrame_Envelope struct {
	Envelope *Envelope `protobuf:"bytes,2,opt,name=envelope,proto3,oneof"`
}

type ServerFrame_Ack struct {
	Ack *DeliveryAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type ServerFrame_Error struct {
	Error *ErrorMessage `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ServerFrame_AuthAck) isServerFrame_Payload() {}

func (*ServerFrame_Envelope) isServerFrame_Payload() {}

func (*ServerFrame_Ack) isServerFrame_Payload() {}

func (*ServerFrame_Error) isServerFrame_Payload() {}

// First frame from the client: the access token and the client's device ID,
// carried in the frame body so they never appear in URLs or access logs.
type AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	DeviceId    string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // client-generated device identifier (its public-key ID)
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_proto_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{2}
}

func (x *AuthRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type AuthAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authenticated bool   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	BlindHashId   string `protobuf:"bytes,2,opt,name=blind_hash_id,json=blindHashId,proto3" json:"blind_hash_id,omitempty"`
}

func (x *AuthAck) Reset() {
	*x = AuthAck{}
	mi := &file_proto_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAck) ProtoMessage() {}

func (x *AuthAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthAck.ProtoReflect.Descriptor instead.
func (*AuthAck) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{3}
}

func (x *AuthAck) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *AuthAck) GetBlindHashId() string {
	if x != nil {
		return x.BlindHashId
	}
	return ""
}

// Ciphertext envelope. [ciphertext] is the E2EE payload produced by the
// client (Signal Protocol) — the relay routes it untouched.
type Envelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId          string `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                         // client-generated UUID v4
	SenderHash     string `protobuf:"bytes,2,opt,name=sender_hash,json=senderHash,proto3" json:"sender_hash,omitempty"`          // authenticated blind_hash_id (server-validated)
	RecipientHash  string `protobuf:"bytes,3,opt,name=recipient_hash,json=recipientHash,proto3" json:"recipient_hash,omitempty"` // target blind_hash_id
	Ciphertext     []byte `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`                            // opaque — relay never inspects
	SentAtMs       uint64 `protobuf:"varint,5,opt,name=sent_at_ms,json=sentAtMs,proto3" json:"sent_at_ms,omitempty"`
	SenderDeviceId string `protobuf:"bytes,6,opt,name=sender_device_id,json=senderDeviceId,proto3" json:"sender_device_id,omitempty"`
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{4}
}

func (x *Envelope) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Envelope) GetSenderHash() string {
	if x != nil {
		return x.SenderHash
	}
	return ""
}

func (x *Envelope) GetRecipientHash() string {
	if x != nil {
		return x.RecipientHash
	}
	return ""
}

func (x *Envelope) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *Envelope) GetSentAtMs() uint64 {
	if x != nil {
		return x.SentAtMs
	}
	return 0
}

func (x *Envelope) GetSenderDeviceId() string {
	if x != nil {
		return x.SenderDeviceId
	}
	return ""
}

// Delivery acknowledgement for a routed message (enables queue purge).
type DeliveryAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId string `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
}

func (x *DeliveryAck) Reset() {
	*x = DeliveryAck{}
	mi := &file_proto_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAck) ProtoMessage() {}

func (x *DeliveryAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAck.ProtoReflect.Descriptor instead.
func (*DeliveryAck) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryAck) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

// Relay error.
type ErrorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_proto_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_relay_proto protoreflect.FileDescriptor

var file_proto_relay_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x69, 0x76, 0x69, 0x63, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79,
	0x2e, 0x76, 0x31, 0x22, 0xb4, 0x01, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x69, 0x76, 0x69, 0x63, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x36, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x69, 0x76, 0x69, 0x63,
	0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x48, 0x00, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x2f,
	0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x69,
	0x76, 0x69, 0x63, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x42,
	0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xed, 0x01, 0x0a, 0x0b, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x61, 0x75,
	0x74, 0x68, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63,
	0x69, 0x76, 0x69, 0x63, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x41, 0x63, 0x6b,
	0x12, 0x36, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x69, 0x76, 0x69, 0x63, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x48, 0x00, 0x52, 0x08,
	0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x2f, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x69, 0x76, 0x69, 0x63, 0x2e, 0x72, 0x65,
	0x6c, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41,
	0x63, 0x6b, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x34, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x69, 0x76, 0x69, 0x63,
	0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42,
	0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4d, 0x0a, 0x0b, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x07, 0x41, 0x75, 0x74,
	0x68, 0x41, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x61, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x62, 0x6c,
	0x69, 0x6e, 0x64, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x48, 0x61, 0x73, 0x68, 0x49, 0x64, 0x22, 0xd1,
	0x01, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6d,
	0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69,
	0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x0a, 0x73, 0x65,
	0x6e, 0x74, 0x5f, 0x61, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x73, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x4d, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x22, 0x24, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x63,
	0x6b, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x0c, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x6e, 0x6b, 0x61, 0x6e, 0x32, 0x32, 0x33, 0x2f, 0x70,
	0x61, 0x72, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_relay_proto_rawDescOnce sync.Once
	file_proto_relay_proto_rawDescData = file_proto_relay_proto_rawDesc
)

func file_proto_relay_proto_rawDescGZIP() []byte {
	file_proto_relay_proto_rawDescOnce.Do(func() {
		file_proto_relay_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_relay_proto_rawDescData)
	})
	return file_proto_relay_proto_rawDescData
}

var file_proto_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_relay_proto_goTypes = []any{
	(*ClientFrame)(nil),  // 0: civic.relay.v1.ClientFrame
	(*ServerFrame)(nil),  // 1: civic.relay.v1.ServerFrame
	(*AuthRequest)(nil),  // 2: civic.relay.v1.AuthRequest
	(*AuthAck)(nil),      // 3: civic.relay.v1.AuthAck
	(*Envelope)(nil),     // 4: civic.relay.v1.Envelope
	(*DeliveryAck)(nil),  // 5: civic.relay.v1.DeliveryAck
	(*ErrorMessage)(nil), // 6: civic.relay.v1.ErrorMessage
}
var file_proto_relay_proto_depIdxs = []int32{
	2, // 0: civic.relay.v1.ClientFrame.auth:type_name -> civic.relay.v1.AuthRequest
	4, // 1: civic.relay.v1.ClientFrame.envelope:type_name -> civic.relay.v1.Envelope
	5, // 2: civic.relay.v1.ClientFrame.ack:type_name -> civic.relay.v1.DeliveryAck
	3, // 3: civic.relay.v1.ServerFrame.auth_ack:type_name -> civic.relay.v1.AuthAck
	4, // 4: civic.relay.v1.ServerFrame.envelope:type_name -> civic.relay.v1.Envelope
	5, // 5: civic.relay.v1.ServerFrame.ack:type_name -> civic.relay.v1.DeliveryAck
	6, // 6: civic.relay.v1.ServerFrame.error:type_name -> civic.relay.v1.ErrorMessage
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_relay_proto_init() }
func file_proto_relay_proto_init() {
	if File_proto_relay_proto != nil {
		return
	}
	file_proto_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientFrame_Auth)(nil),
		(*ClientFrame_Envelope)(nil),
		(*ClientFrame_Ack)(nil),
	}
	file_proto_relay_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerFrame_AuthAck)(nil),
		(*ServerFrame_Envelope)(nil),
		(*ServerFrame_Ack)(nil),
		(*ServerFrame_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_relay_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_relay_proto_goTypes,
		DependencyIndexes: file_proto_relay_proto_depIdxs,
		MessageInfos:      file_proto_relay_proto_msgTypes,
	}.Build()
	File_proto_relay_proto = out.File
	file_proto_relay_proto_rawDesc = nil
	file_proto_relay_proto_goTypes = nil
	file_proto_relay_proto_depIdxs = nil
}
