// Civic Commons Messaging Relay wire protocol (Task 4.4).
//
// Protocol Buffers over WebSocket frames (techstack §5.3). The client MUST
// authenticate in the FIRST frame (AuthRequest) — never in the URL, since
// query strings are logged by proxies.
//
// ZERO-KNOWLEDGE CONSTRAINT: the Envelope.ciphertext field is OPAQUE. The
// relay MUST never deserialize, decrypt, or inspect it — it routes bytes.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/relay.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientFrame is every message a client sends to the relay.
type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientFrame_Auth
	//	*ClientFrame_Envelope
	//	*ClientFrame_Ack
	//	*ClientFrame_Typing
	//	*ClientFrame_ReadReceipt
	Payload       isClientFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_proto_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFrame) GetPayload() isClientFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientFrame) GetAuth() *AuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *ClientFrame) GetEnvelope() *Envelope {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_Envelope); ok {
			return x.Envelope
		}
	}
	return nil
}

func (x *ClientFrame) GetAck() *DeliveryAck {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ClientFrame) GetTyping() *TypingIndicator {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

func (x *ClientFrame) GetReadReceipt() *ReadReceipt {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_ReadReceipt); ok {
			return x.ReadReceipt
		}
	}
	return nil
}

type isClientFrame_Payload interface {
	isClientFrame_Payload()
}

type ClientFrame_Auth struct {
	Auth *AuthRequest `protobuf:"bytes,1,opt,name=auth,proto3,oneof"`
}

type ClientFrame_Envelope struct {
	Envelope *Envelope `protobuf:"bytes,2,opt,name=envelope,proto3,oneof"`
}

type ClientFrame_Ack struct {
	Ack *DeliveryAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type ClientFrame_Typing struct {
	Typing *TypingIndicator `protobuf:"bytes,4,opt,name=typing,proto3,oneof"`
}

type ClientFrame_ReadReceipt struct {
	ReadReceipt *ReadReceipt `protobuf:"bytes,5,opt,name=read_receipt,json=readReceipt,proto3,oneof"`
}

func (*ClientFrame_Auth) isClientFrame_Payload() {}

func (*ClientFrame_Envelope) isClientFrame_Payload() {}

func (*ClientFrame_Ack) isClientFrame_Payload() {}

func (*ClientFrame_Typing) isClientFrame_Payload() {}

func (*ClientFrame_ReadReceipt) isClientFrame_Payload() {}

// ServerFrame is every message the relay sends to a client.
type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerFrame_AuthAck
	//	*ServerFrame_Envelope
	//	*ServerFrame_Ack
	//	*ServerFrame_Error
	//	*ServerFrame_Typing
	//	*ServerFrame_ReadReceipt
	Payload       isServerFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_proto_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{1}
}

func (x *ServerFrame) GetPayload() isServerFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerFrame) GetAuthAck() *AuthAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_AuthAck); ok {
			return x.AuthAck
		}
	}
	return nil
}

func (x *ServerFrame) GetEnvelope() *Envelope {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_Envelope); ok {
			return x.Envelope
		}
	}
	return nil
}

func (x *ServerFrame) GetAck() *DeliveryAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerFrame) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerFrame) GetTyping() *TypingIndicator {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

func (x *ServerFrame) GetReadReceipt() *ReadReceipt {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_ReadReceipt); ok {
			return x.ReadReceipt
		}
	}
	return nil
}

type isServerFrame_Payload interface {
	isServerFrame_Payload()
}

type ServerFrame_AuthAck struct {
	AuthAck *AuthAck `protobuf:"bytes,1,opt,name=auth_ack,json=authAck,proto3,oneof"`
}

type ServerFrame_Envelope struct {
	Envelope *Envelope `protobuf:"bytes,2,opt,name=envelope,proto3,oneof"`
}

type ServerFrame_Ack struct {
	Ack *DeliveryAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type ServerFrame_Error struct {
	Error *ErrorMessage `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type ServerFrame_Typing struct {
	Typing *TypingIndicator `protobuf:"bytes,5,opt,name=typing,proto3,oneof"`
}

type ServerFrame_ReadReceipt struct {
	ReadReceipt *ReadReceipt `protobuf:"bytes,6,opt,name=read_receipt,json=readReceipt,proto3,oneof"`
}

func (*ServerFrame_AuthAck) isServerFrame_Payload() {}

func (*ServerFrame_Envelope) isServerFrame_Payload() {}

func (*ServerFrame_Ack) isServerFrame_Payload() {}

func (*ServerFrame_Error) isServerFrame_Payload() {}

func (*ServerFrame_Typing) isServerFrame_Payload() {}

func (*ServerFrame_ReadReceipt) isServerFrame_Payload() {}

// First frame from the client: the access token and the client's device ID,
// carried in the frame body so they never appear in URLs or access logs.
type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // client-generated device identifier (its public-key ID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_proto_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{2}
}

func (x *AuthRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type AuthAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authenticated bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	BlindHashId   string                 `protobuf:"bytes,2,opt,name=blind_hash_id,json=blindHashId,proto3" json:"blind_hash_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthAck) Reset() {
	*x = AuthAck{}
	mi := &file_proto_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAck) ProtoMessage() {}

func (x *AuthAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthAck.ProtoReflect.Descriptor instead.
func (*AuthAck) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{3}
}

func (x *AuthAck) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *AuthAck) GetBlindHashId() string {
	if x != nil {
		return x.BlindHashId
	}
	return ""
}

// Ciphertext envelope. [ciphertext] is the E2EE payload produced by the
// client (Signal Protocol) — the relay routes it untouched.
type Envelope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgId          string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                         // client-generated UUID v4
	SenderHash     string                 `protobuf:"bytes,2,opt,name=sender_hash,json=senderHash,proto3" json:"sender_hash,omitempty"`          // authenticated blind_hash_id (server-validated)
	RecipientHash  string                 `protobuf:"bytes,3,opt,name=recipient_hash,json=recipientHash,proto3" json:"recipient_hash,omitempty"` // target blind_hash_id
	Ciphertext     []byte                 `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`                            // opaque — relay never inspects
	SentAtMs       uint64                 `protobuf:"varint,5,opt,name=sent_at_ms,json=sentAtMs,proto3" json:"sent_at_ms,omitempty"`
	SenderDeviceId string                 `protobuf:"bytes,6,opt,name=sender_device_id,json=senderDeviceId,proto3" json:"sender_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{4}
}

func (x *Envelope) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Envelope) GetSenderHash() string {
	if x != nil {
		return x.SenderHash
	}
	return ""
}

func (x *Envelope) GetRecipientHash() string {
	if x != nil {
		return x.RecipientHash
	}
	return ""
}

func (x *Envelope) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *Envelope) GetSentAtMs() uint64 {
	if x != nil {
		return x.SentAtMs
	}
	return 0
}

func (x *Envelope) GetSenderDeviceId() string {
	if x != nil {
		return x.SenderDeviceId
	}
	return ""
}

// Delivery acknowledgement for a routed message (enables queue purge).
type DeliveryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryAck) Reset() {
	*x = DeliveryAck{}
	mi := &file_proto_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAck) ProtoMessage() {}

func (x *DeliveryAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAck.ProtoReflect.Descriptor instead.
func (*DeliveryAck) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryAck) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

// Relay error.
type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_proto_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Typing indicator — the sender is actively composing a message.
// Routed to the recipient; never queued offline (ephemeral).
type TypingIndicator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientHash string                 `protobuf:"bytes,1,opt,name=recipient_hash,json=recipientHash,proto3" json:"recipient_hash,omitempty"` // target blind_hash_id
	IsTyping      bool                   `protobuf:"varint,2,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`               // true = started, false = stopped
	SenderHash    string                 `protobuf:"bytes,3,opt,name=sender_hash,json=senderHash,proto3" json:"sender_hash,omitempty"`          // who is typing (populated by server)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypingIndicator) Reset() {
	*x = TypingIndicator{}
	mi := &file_proto_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingIndicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingIndicator) ProtoMessage() {}

func (x *TypingIndicator) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingIndicator.ProtoReflect.Descriptor instead.
func (*TypingIndicator) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{7}
}

func (x *TypingIndicator) GetRecipientHash() string {
	if x != nil {
		return x.RecipientHash
	}
	return ""
}

func (x *TypingIndicator) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

func (x *TypingIndicator) GetSenderHash() string {
	if x != nil {
		return x.SenderHash
	}
	return ""
}

// Read receipt — the recipient has seen messages up to [last_msg_id].
// Routed to the sender; never queued offline (ephemeral).
type ReadReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderHash    string                 `protobuf:"bytes,1,opt,name=sender_hash,json=senderHash,proto3" json:"sender_hash,omitempty"` // the original sender (receipt target)
	LastMsgId     string                 `protobuf:"bytes,2,opt,name=last_msg_id,json=lastMsgId,proto3" json:"last_msg_id,omitempty"`  // the most recent msg_id the reader has seen
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReceipt) Reset() {
	*x = ReadReceipt{}
	mi := &file_proto_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReceipt) ProtoMessage() {}

func (x *ReadReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReceipt.ProtoReflect.Descriptor instead.
func (*ReadReceipt) Descriptor() ([]byte, []int) {
	return file_proto_relay_proto_rawDescGZIP(), []int{8}
}

func (x *ReadReceipt) GetSenderHash() string {
	if x != nil {
		return x.SenderHash
	}
	return ""
}

func (x *ReadReceipt) GetLastMsgId() string {
	if x != nil {
		return x.LastMsgId
	}
	return ""
}

var File_proto_relay_proto protoreflect.FileDescriptor

const file_proto_relay_proto_rawDesc = "" +
	"\n" +
	"\x11proto/relay.proto\x12\x0ecivic.relay.v1\"\xb1\x02\n" +
	"\vClientFrame\x121\n" +
	"\x04auth\x18\x01 \x01(\v2\x1b.civic.relay.v1.AuthRequestH\x00R\x04auth\x126\n" +
	"\benvelope\x18\x02 \x01(\v2\x18.civic.relay.v1.EnvelopeH\x00R\benvelope\x12/\n" +
	"\x03ack\x18\x03 \x01(\v2\x1b.civic.relay.v1.DeliveryAckH\x00R\x03ack\x129\n" +
	"\x06typing\x18\x04 \x01(\v2\x1f.civic.relay.v1.TypingIndicatorH\x00R\x06typing\x12@\n" +
	"\fread_receipt\x18\x05 \x01(\v2\x1b.civic.relay.v1.ReadReceiptH\x00R\vreadReceiptB\t\n" +
	"\apayload\"\xea\x02\n" +
	"\vServerFrame\x124\n" +
	"\bauth_ack\x18\x01 \x01(\v2\x17.civic.relay.v1.AuthAckH\x00R\aauthAck\x126\n" +
	"\benvelope\x18\x02 \x01(\v2\x18.civic.relay.v1.EnvelopeH\x00R\benvelope\x12/\n" +
	"\x03ack\x18\x03 \x01(\v2\x1b.civic.relay.v1.DeliveryAckH\x00R\x03ack\x124\n" +
	"\x05error\x18\x04 \x01(\v2\x1c.civic.relay.v1.ErrorMessageH\x00R\x05error\x129\n" +
	"\x06typing\x18\x05 \x01(\v2\x1f.civic.relay.v1.TypingIndicatorH\x00R\x06typing\x12@\n" +
	"\fread_receipt\x18\x06 \x01(\v2\x1b.civic.relay.v1.ReadReceiptH\x00R\vreadReceiptB\t\n" +
	"\apayload\"M\n" +
	"\vAuthRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"S\n" +
	"\aAuthAck\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated\x12\"\n" +
	"\rblind_hash_id\x18\x02 \x01(\tR\vblindHashId\"\xd1\x01\n" +
	"\bEnvelope\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1f\n" +
	"\vsender_hash\x18\x02 \x01(\tR\n" +
	"senderHash\x12%\n" +
	"\x0erecipient_hash\x18\x03 \x01(\tR\rrecipientHash\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\x12\x1c\n" +
	"\n" +
	"sent_at_ms\x18\x05 \x01(\x04R\bsentAtMs\x12(\n" +
	"\x10sender_device_id\x18\x06 \x01(\tR\x0esenderDeviceId\"$\n" +
	"\vDeliveryAck\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\"<\n" +
	"\fErrorMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"v\n" +
	"\x0fTypingIndicator\x12%\n" +
	"\x0erecipient_hash\x18\x01 \x01(\tR\rrecipientHash\x12\x1b\n" +
	"\tis_typing\x18\x02 \x01(\bR\bisTyping\x12\x1f\n" +
	"\vsender_hash\x18\x03 \x01(\tR\n" +
	"senderHash\"N\n" +
	"\vReadReceipt\x12\x1f\n" +
	"\vsender_hash\x18\x01 \x01(\tR\n" +
	"senderHash\x12\x1e\n" +
	"\vlast_msg_id\x18\x02 \x01(\tR\tlastMsgIdB0Z.github.com/kankan223/pari/services/proto;protob\x06proto3"

var (
	file_proto_relay_proto_rawDescOnce sync.Once
	file_proto_relay_proto_rawDescData []byte
)

func file_proto_relay_proto_rawDescGZIP() []byte {
	file_proto_relay_proto_rawDescOnce.Do(func() {
		file_proto_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_relay_proto_rawDesc), len(file_proto_relay_proto_rawDesc)))
	})
	return file_proto_relay_proto_rawDescData
}

var file_proto_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_relay_proto_goTypes = []any{
	(*ClientFrame)(nil),     // 0: civic.relay.v1.ClientFrame
	(*ServerFrame)(nil),     // 1: civic.relay.v1.ServerFrame
	(*AuthRequest)(nil),     // 2: civic.relay.v1.AuthRequest
	(*AuthAck)(nil),         // 3: civic.relay.v1.AuthAck
	(*Envelope)(nil),        // 4: civic.relay.v1.Envelope
	(*DeliveryAck)(nil),     // 5: civic.relay.v1.DeliveryAck
	(*ErrorMessage)(nil),    // 6: civic.relay.v1.ErrorMessage
	(*TypingIndicator)(nil), // 7: civic.relay.v1.TypingIndicator
	(*ReadReceipt)(nil),     // 8: civic.relay.v1.ReadReceipt
}
var file_proto_relay_proto_depIdxs = []int32{
	2,  // 0: civic.relay.v1.ClientFrame.auth:type_name -> civic.relay.v1.AuthRequest
	4,  // 1: civic.relay.v1.ClientFrame.envelope:type_name -> civic.relay.v1.Envelope
	5,  // 2: civic.relay.v1.ClientFrame.ack:type_name -> civic.relay.v1.DeliveryAck
	7,  // 3: civic.relay.v1.ClientFrame.typing:type_name -> civic.relay.v1.TypingIndicator
	8,  // 4: civic.relay.v1.ClientFrame.read_receipt:type_name -> civic.relay.v1.ReadReceipt
	3,  // 5: civic.relay.v1.ServerFrame.auth_ack:type_name -> civic.relay.v1.AuthAck
	4,  // 6: civic.relay.v1.ServerFrame.envelope:type_name -> civic.relay.v1.Envelope
	5,  // 7: civic.relay.v1.ServerFrame.ack:type_name -> civic.relay.v1.DeliveryAck
	6,  // 8: civic.relay.v1.ServerFrame.error:type_name -> civic.relay.v1.ErrorMessage
	7,  // 9: civic.relay.v1.ServerFrame.typing:type_name -> civic.relay.v1.TypingIndicator
	8,  // 10: civic.relay.v1.ServerFrame.read_receipt:type_name -> civic.relay.v1.ReadReceipt
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_relay_proto_init() }
func file_proto_relay_proto_init() {
	if File_proto_relay_proto != nil {
		return
	}
	file_proto_relay_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientFrame_Auth)(nil),
		(*ClientFrame_Envelope)(nil),
		(*ClientFrame_Ack)(nil),
		(*ClientFrame_Typing)(nil),
		(*ClientFrame_ReadReceipt)(nil),
	}
	file_proto_relay_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerFrame_AuthAck)(nil),
		(*ServerFrame_Envelope)(nil),
		(*ServerFrame_Ack)(nil),
		(*ServerFrame_Error)(nil),
		(*ServerFrame_Typing)(nil),
		(*ServerFrame_ReadReceipt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_relay_proto_rawDesc), len(file_proto_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_relay_proto_goTypes,
		DependencyIndexes: file_proto_relay_proto_depIdxs,
		MessageInfos:      file_proto_relay_proto_msgTypes,
	}.Build()
	File_proto_relay_proto = out.File
	file_proto_relay_proto_goTypes = nil
	file_proto_relay_proto_depIdxs = nil
}
