import 'dart:typed_data';
import 'package:cryptography/cryptography.dart';
import 'package:civic_commons/crypto/crypto_service.dart';
import 'package:civic_commons/crypto/secure_key_storage.dart';
import 'models.dart';

/// Prekey management system for Signal Protocol
///
/// Manages signed prekey rotation (7 days) and one-time prekey batches (100 keys)
class PrekeyManager {
  final CryptoService _cryptoService;
  final SecureKeyStorage _secureStorage;

  // Rotation period for signed prekeys (7 days)
  static const Duration _signedPreKeyRotationPeriod = Duration(days: 7);

  // Batch size for one-time prekeys (100 keys)
  static const int _oneTimePreKeyBatchSize = 100;

  // Key ID counters
  int _signedPreKeyId = 0;
  int _oneTimePreKeyId = 0;

  PrekeyManager({
    required CryptoService cryptoService,
    required SecureKeyStorage secureStorage,
  })  : _cryptoService = cryptoService,
        _secureStorage = secureStorage;  /// The Ed25519 identity key pair used for signing prekeys.
  /// Lazily generated on first access and cached in memory.
  SimpleKeyPair? _identityKeyPair;

  /// Get or generate the Ed25519 identity key pair.
  ///
  /// SECURITY: The private key is generated once and held in memory for
  /// the process lifetime. In production, it would be stored in hardware-
  /// backed secure storage. The public key is published in prekey bundles.
  Future<SimpleKeyPair> _getIdentityKeyPair() async {
    if (_identityKeyPair != null) return _identityKeyPair!;
    _identityKeyPair = await _cryptoService.generateEd25519KeyPair();
    return _identityKeyPair!;
  }

  /// Get the Ed25519 identity public key (32 bytes).
  Future<Uint8List> getIdentityPublicKey() async {
    final kp = await _getIdentityKeyPair();
    return Uint8List.fromList((await kp.extractPublicKey()).bytes);
  }

  /// Generate a new signed prekey, signed with our Ed25519 identity key.
  ///
  /// Returns: A SignedPreKey with 7-day expiration and a valid Ed25519
  /// signature over the signed prekey's public key.
  ///
  /// Security: Private key is stored in hardware-backed secure storage.
  /// The signature proves the prekey was generated by the identity key
  /// holder, preventing MITM substitution attacks.
  Future<SignedPreKey> generateSignedPreKey() async {
    // Generate Curve25519 key pair for the signed prekey
    final keyPair = await _cryptoService.generateCurve25519KeyPair();

    // Extract keys
    final publicKey =
        Uint8List.fromList((await keyPair.extractPublicKey()).bytes);
    final privateKey = Uint8List.fromList(await keyPair.extractPrivateKeyBytes());

    // Sign the signed prekey's public key with our Ed25519 identity key.
    // The signature covers: key_id (4 bytes LE) || public_key (32 bytes).
    final identityKp = await _getIdentityKeyPair();
    final ed25519 = Ed25519();
    final dataToSign = BytesBuilder();
    final keyId = _signedPreKeyId;
    dataToSign.addByte((keyId >> 24) & 0xff);
    dataToSign.addByte((keyId >> 16) & 0xff);
    dataToSign.addByte((keyId >> 8) & 0xff);
    dataToSign.addByte(keyId & 0xff);
    dataToSign.add(publicKey);
    final signature = await ed25519.sign(
      dataToSign.toBytes(),
      keyPair: identityKp,
    );
    final signatureBytes = Uint8List.fromList(signature.bytes);

    // Create signed prekey with metadata
    final now = DateTime.now();
    final signedPreKey = SignedPreKey(
      keyId: _signedPreKeyId++,
      publicKey: publicKey,
      privateKey: privateKey,
      createdAt: now,
      expiresAt: now.add(_signedPreKeyRotationPeriod),
      signature: signatureBytes,
    );

    // Store in secure storage
    await _secureStorage.storeSignedPreKey(keyPair, signedPreKey.keyId);

    // Securely wipe private key from memory
    privateKey.fillRange(0, privateKey.length, 0);

    return signedPreKey;
  }

  /// Generate a batch of one-time prekeys
  ///
  /// Returns: List of OneTimePreKey objects
  ///
  /// Security: Private keys are stored in hardware-backed secure storage
  Future<List<OneTimePreKey>> generateOneTimePreKeyBatch() async {
    final prekeys = <OneTimePreKey>[];

    for (int i = 0; i < _oneTimePreKeyBatchSize; i++) {
      // Generate Curve25519 key pair
      final keyPair = await _cryptoService.generateCurve25519KeyPair();

      // Extract keys
      final publicKey =
          Uint8List.fromList((await keyPair.extractPublicKey()).bytes);
      final privateKey =
          Uint8List.fromList(await keyPair.extractPrivateKeyBytes());

      // Create one-time prekey
      final prekey = OneTimePreKey(
        keyId: _oneTimePreKeyId++,
        publicKey: publicKey,
        privateKey: privateKey,
      );

      // Store in secure storage
      await _secureStorage.storeOneTimePreKey(keyPair, prekey.keyId);

      // Securely wipe private key from memory
      privateKey.fillRange(0, privateKey.length, 0);

      prekeys.add(prekey);
    }

    return prekeys;
  }

  /// Get the current signed prekey
  ///
  /// Returns: The current signed prekey, or null if none exists
  Future<SignedPreKey?> getCurrentSignedPreKey() async {
    // Check if signed prekey with ID 0 exists
    final keyPair = await _secureStorage.getSignedPreKey(0);
    if (keyPair == null) {
      return null;
    }

    final publicKey =
        Uint8List.fromList((await keyPair.extractPublicKey()).bytes);
    final privateKey =
        Uint8List.fromList(await keyPair.extractPrivateKeyBytes());

    final now = DateTime.now();
    final signedPreKey = SignedPreKey(
      keyId: 0,
      publicKey: publicKey,
      privateKey: privateKey,
      createdAt: now.subtract(_signedPreKeyRotationPeriod),
      expiresAt: now.add(_signedPreKeyRotationPeriod),
    );

    // Securely wipe private key from memory
    privateKey.fillRange(0, privateKey.length, 0);

    return signedPreKey;
  }

  /// Check if signed prekey needs rotation
  ///
  /// Returns: true if the current signed prekey needs rotation
  Future<bool> needsSignedPreKeyRotation() async {
    final currentPrekey = await getCurrentSignedPreKey();
    if (currentPrekey == null) {
      return true; // No prekey exists, need to generate one
    }
    return currentPrekey.needsRotation();
  }

  /// Rotate signed prekey
  ///
  /// Returns: The new signed prekey
  ///
  /// Security: Old prekey is kept for a grace period to handle in-flight messages
  Future<SignedPreKey> rotateSignedPreKey() async {
    // Generate new signed prekey
    final newPrekey = await generateSignedPreKey();

    // In production, we would keep the old prekey for a grace period
    // For now, we'll just generate the new one

    return newPrekey;
  }

  /// Get a one-time prekey for use
  ///
  /// Returns: A one-time prekey, or null if none available
  ///
  /// Security: The prekey is consumed (deleted) after retrieval
  Future<OneTimePreKey?> getOneTimePreKey() async {
    // Try to consume a one-time prekey starting from the lowest ID
    for (int i = 0; i < _oneTimePreKeyId; i++) {
      final keyPair = await _secureStorage.consumeOneTimePreKey(i);
      if (keyPair != null) {
        final publicKey =
            Uint8List.fromList((await keyPair.extractPublicKey()).bytes);
        final privateKey =
            Uint8List.fromList(await keyPair.extractPrivateKeyBytes());

        final prekey = OneTimePreKey(
          keyId: i,
          publicKey: publicKey,
          privateKey: privateKey,
        );

        // Securely wipe private key from memory
        privateKey.fillRange(0, privateKey.length, 0);

        return prekey;
      }
    }

    return null; // No one-time prekeys available
  }

  /// Check if one-time prekeys need to be replenished
  ///
  /// Returns: true if one-time prekey count is below threshold
  Future<bool> needsOneTimePreKeyReplenishment() async {
    // In production, we would check the actual count
    // For now, we'll assume we need replenishment if we've used more than 50%
    return (_oneTimePreKeyId % (_oneTimePreKeyBatchSize ~/ 2)) == 0;
  }

  /// Replenish one-time prekeys
  ///
  /// Returns: The new batch of one-time prekeys
  Future<List<OneTimePreKey>> replenishOneTimePreKeys() async {
    return await generateOneTimePreKeyBatch();
  }

  /// Create a PreKeyBundle for sharing
  ///
  /// Parameters:
  /// - registrationId: The user's registration ID
  /// - identityKey: The user's Curve25519 identity public key
  ///
  /// Returns: A PreKeyBundle ready for API transmission
  ///
  /// Security: Only contains public keys, no private keys. The signed
  /// prekey is signed with the Ed25519 identity key for verification.
  Future<PreKeyBundle> createPreKeyBundle(
    String registrationId,
    Uint8List identityKey,
  ) async {
    // Get current signed prekey
    final signedPreKey = await getCurrentSignedPreKey();
    if (signedPreKey == null) {
      throw StateError('No signed prekey available. Generate one first.');
    }

    // Get a one-time prekey if available
    final oneTimePreKey = await getOneTimePreKey();

    // Get the Ed25519 identity public key for the bundle
    final ed25519PublicKey = await getIdentityPublicKey();

    // Create bundle with real signature from generateSignedPreKey
    final bundle = PreKeyBundle(
      registrationId: registrationId,
      identityKey: identityKey,
      ed25519IdentityKey: ed25519PublicKey,
      signedPreKeyId: signedPreKey.keyId,
      signedPreKey: signedPreKey.publicKey,
      signedPreKeySignature: signedPreKey.signature ?? Uint8List(64),
      oneTimePreKeyId: oneTimePreKey?.keyId,
      oneTimePreKey: oneTimePreKey?.publicKey,
    );

    return bundle;
  }

  /// Delete all prekeys (for account deletion or duress PIN)
  ///
  /// Security: This is a destructive operation that cannot be undone
  Future<void> deleteAllPrekeys() async {
    await _secureStorage.deleteAllKeys();
    _signedPreKeyId = 0;
    _oneTimePreKeyId = 0;
  }
}
