import 'dart:async';

import '../domain/batch_chunker.dart';
import '../domain/sync_worker.dart';
import '../../repository/domain/exponential_backoff.dart';
import '../../repository/domain/local_first_repository.dart';
import '../../repository/domain/sync_conflict_resolver.dart';
import '../../repository/domain/sync_queue_repository.dart';
import '../../repository/domain/sync_sink.dart';

/// Background sync worker that processes pending queue items (Task 3.4;
/// hardening in Task 5.2).
///
/// Drains the local sync queue in bounded batches (max 10 items) and pushes
/// each item through the injected [SyncSink] — the repository layer's ONLY
/// network boundary. Marks items in-progress before the push and
/// success/failed after, so a crash mid-batch leaves the queue consistent.
///
/// Task 5.2 additions:
/// - **Deterministic retry with backoff + jitter:** [runOnce] drains not just
///   `pending` items but also `failed` items whose backoff window has
///   elapsed — [SyncQueueRepository.getRetryable] gates each failed item on
///   `lastAttemptAt + delayForRetryWithJitter(retryCount) <= now`. The
///   jittered [ExponentialBackoff] is the ACTUAL retry gate, so a fleet of
///   reconnecting devices retries decorrelated instead of in lockstep.
/// - **Crash recovery:** [runOnce] first calls
///   [SyncQueueRepository.recoverInterrupted] so items stranded `in_progress`
///   by a previous crash are retried instead of lost.
/// - **Aggressive timeout:** each push is bounded by [requestTimeout] (10s per
///   the master plan); a timed-out push is treated as a failure and retried
///   with backoff — a hung connection can never stall the whole drain.
/// - **Idempotency:** the transport attaches `Idempotency-Key: <item.id>`
///   (item ids are UUID v4 idempotency keys generated by the repository
///   layer's `IdempotencyKeyGenerator`), so the server dedupes retried pushes.
///
/// SECURITY CHECKPOINT (Task 3.4/5.2):
/// - The worker performs NO direct HTTP calls; the only outbound path is the
///   injected [SyncSink], which receives opaque sealed payloads.
/// - It reads exclusively from the local encrypted queue (offline-first).
/// - It never logs raw payloads.
///
/// CONFLICT HANDLING (Task 5.5): when the sink returns a
/// [SyncPushOutcome.conflict], the worker routes local-vs-remote through the
/// injected [SyncConflictResolver] (itself deterministic): local wins → the
/// item is kept for retry; remote wins / merge → the item is DROPPED from
/// the queue as superseded (the entity converges from the remote on the next
/// pull). Superseded items are counted in [SyncResult.conflicts].
class BackgroundSyncWorker implements SyncWorker {
  final SyncQueueRepository _queue;
  final SyncSink _sink;
  final int _maxBatchSize;
  final ExponentialBackoff _backoff;
  final DateTime Function() _clock;
  final SyncConflictResolver _conflictResolver;

  BackgroundSyncWorker({
    required SyncQueueRepository queue,
    required SyncSink sink,
    int maxBatchSize = BatchChunker.defaultMaxBatchSize,
    this.requestTimeout = const Duration(seconds: 10),
    ExponentialBackoff? backoff,
    DateTime Function()? clock,
    SyncConflictResolver conflictResolver = const SyncConflictResolver(),
  })  : _queue = queue,
        _sink = sink,
        _maxBatchSize = maxBatchSize,
        _backoff = backoff ?? const ExponentialBackoff(),
        _clock = clock ?? DateTime.now,
        _conflictResolver = conflictResolver;

  /// Maximum time a single [SyncSink.push] may take before it is treated as
  /// failed (aggressive 10s limit per the master plan).
  final Duration requestTimeout;

  @override
  Future<SyncResult> runOnce() async {
    // Crash recovery first: items stranded in_progress by a killed run are
    // reset to pending so this drain retries them.
    await _queue.recoverInterrupted();

    final now = _clock();
    // 30-day retention (Task 5.6): stale mutations past the offline window
    // are purged BEFORE the drain so they are never pushed (the server's own
    // 30-day queue TTL would reject them anyway).
    await _queue.purgeExpired(now: now);
    // Deterministic retry: pending items + failed items whose backoff window
    // has elapsed (jittered — decorrelated across a fleet).
    final pending = await _queue.getPending();
    final retryable = await _queue.getRetryable(
      now: now,
      retryDelay: (retries) => _backoff.delayForRetryWithJitter(retries),
    );
    final toSend = [...pending, ...retryable];
    var pushed = 0;
    var failed = 0;
    var conflicts = 0;

    // Process in bounded batches so each network burst touches ≤10 items.
    for (final batch in BatchChunker.chunk(
      toSend,
      maxBatchSize: _maxBatchSize,
    )) {
      for (final item in batch) {
        await _queue.markInProgress(item.id);
        // A THROWN sink error or a TIMEOUT is the same failure as a rejected
        // push: mark the item failed (retryCount++) so it is never left stuck
        // in in_progress and can be retried after its backoff window.
        SyncPushOutcome outcome;
        try {
          outcome = await _sink.push(item).timeout(requestTimeout);
        } catch (_) {
          outcome = const SyncPushOutcome.rejected();
        }

        final resolution =
            _conflictResolver.resolve(item: item, outcome: outcome);
        switch (resolution.disposition) {
          case SyncDisposition.success:
            await _queue.markSuccess(item.id);
            pushed++;
          case SyncDisposition.retry:
            await _queue.markFailed(item.id);
            failed++;
          case SyncDisposition.superseded:
            // Conflict resolved in the remote's favour (or merged): the local
            // mutation is obsolete — drop it so it is never re-pushed.
            await _queue.delete(item.id);
            conflicts++;
        }
      }
    }
    return SyncResult(pushed: pushed, failed: failed, conflicts: conflicts);
  }
}
