apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
spec:
  serviceName: {{ .Chart.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        fsGroup: 1001
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Chart.Name }}:latest"
        securityContext:
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
